"""Stores details of movies and displays them on a website.
Creates six Movie objects, initialising these objects with title, storyline, poster image link, video trailer link and release date."""

import fresh_tomatoes
import media

i_love_you_man = media.Movie("I Love You, Man", "83%", "yes", "John Hamburg", "A successful real estate agent, who upon getting engaged to the woman of his dreams, Zooey, discovers, to his dismay and chagrin, that he has no male friend close enough to serve as his Best Man. Peter immediately sets out to rectify the situation, embarking on a series of bizarre and awkward 'man-dates', before meeting Sydney Fife, a charming, opinionated man with whom he instantly bonds. But, the closer the two men get, the more Peter's relationship with Zooey suffers, ultimately forcing him to choose between his fiancee and his new found 'bro', in a story that comically explores what it truly means to be a friend.","http://www.freemovieposters.net/posters/i_love_you_man_2009_2373_poster.jpg","https://www.youtube.com/watch?v=um5DuTLzw-I")

coco = media.Movie("Coco", "97%", "yes", "Lee Unkrich, Adrian Molina", "Despite his family's baffling generations-old ban on music, Miguel (voice of newcomer Anthony Gonzalez) dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz (voice of Benjamin Bratt). Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector (voice of Gael Garcia Bernal), and together, they set off on an extraordinary journey to unlock the real story behind Miguel's family history.", "https://cuindependent.com/new/wp-content/uploads/2017/11/coco-movie-poster-1.png", "https://www.youtube.com/watch?v=Ga6RYejo6Hk&t=72s")

waiting_for_guffman = media.Movie("Waiting for Guffman", "91%", "yes", "Christopher Guest", "An aspiring director and the marginally talented amateur cast of a hokey small-town Missouri musical production go overboard when they learn that someone from Broadway will be in attendance.", "https://lunkiandsika.files.wordpress.com/2011/08/waiting-for-guffman-christopher-guest-poster.png?w=580&h=842", "https://www.youtube.com/watch?v=s0Ml4u3hLlY")

sister_act = media.Movie("Sister Act", "74%", "yes","Emile Ardolino", "Deloris Van Cartier, a lounge singer at a club in Reno, Nevada, witnesses her mobster boyfriend Vince LaRocca execute his chauffeur as a rat. Lieutenant Eddie Souther persuades her to go into a witness protection programme at St. Katherine's Parish, a convent in a run-down San Francisco neighborhood. The stoic Reverend Mother finds Deloris uncouth, but Monsignor O'Hara, the neighborhood priest, persuades her to accept her.", "https://www.dvdsreleasedates.com/posters/300/S/Sister-Act-1992.jpg", "https://www.youtube.com/watch?v=ghHE_kVWXxM")

the_frighteners = media.Movie("The Frighteners", "62%", "no", "Peter Jackson", "After a tragic car accident kills his wife, a man discovers he can communicate with the dead to con people. However, when a demonic spirit appears, he may be the only one who can stop it from killing the living and the dead.", "https://roosterillusionreviews.files.wordpress.com/2015/10/frighteners_poster_01.jpg", "https://www.youtube.com/watch?v=lKWiQLwr9Xs")

howls_moving_castle = media.Movie("Howl's Moving Castle", "87%", "yes", "Hayao Miyazaki", "Sophie, a diligent teenage girl working in her family's hat shop, finds her life thrown into turmoil when a handsome-but-mysterious wizard named Howl sweeps her off her feet. This innocent encounter enrages the vain and conniving Witch of the Waste, who transforms Sophie into a 90-year-old woman. Sophie's efforts to break the curse bring her to Howl's magical moving castle, where she befriends Markl, Howl's apprentice, and the hot-headed fire demon Calcifer. Her love and support have a major impact on Howl, who can be maddeningly self-indulgent and singularly noble. He defies royal orders to participate in a meaningless war and risks his life to bring peace to the kingdom.", "https://assets.rbl.ms/14814555/980x.jpg", "https://www.youtube.com/watch?v=iwROgK94zcM")

movies = [coco, the_frighteners, howls_moving_castle, i_love_you_man, sister_act, waiting_for_guffman]
fresh_tomatoes.open_movies_page(movies)